language: cpp
compiler:
- g++
env:
  matrix:
    - ARRAY_SIZE="15000" SORT_OPTION="DESC"
    - ARRAY_SIZE="15000" SORT_OPTION="ASC"
    - ARRAY_SIZE="15000" SORT_OPTION="NORMAL"
before_script:
  - make work
script:
  - ./runTests.sh ${ARRAY_SIZE} ${SORT_OPTION}
