language: cpp
compiler:
- g++
env:
  matrix:
    - RUN_OPTION="bubbleSort"
    - RUN_OPTION="insertionSort"
    - RUN_OPTION="selectionSort"
    - RUN_OPTION="quickSort"
    - RUN_OPTION="heapSort"
    - RUN_OPTION="shellSort"
script:
  - make