#!/usr/bin/env bash
ARRAY_SIZE=15000
SORT_OPTION="NORMAL"
echo ${SORT_OPTION}
./runTests.sh ${ARRAY_SIZE} ${SORT_OPTION}
SORT_OPTION="DESC"
echo ${SORT_OPTION}
./runTests.sh ${ARRAY_SIZE} ${SORT_OPTION}
SORT_OPTION="ASC"
echo ${SORT_OPTION}
./runTests.sh ${ARRAY_SIZE} ${SORT_OPTION}